language: python
python:
  - 2.7
  - 3.5
  - 3.6

install:
 - pip install pandas
 - pip install pytest
 - pip install codecov
 - pip install pytest-cov

script: pytest --cov-report term --cov=investpy src/

after_success:
 - codecov
